import { Component } from '@angular/core';
import { HeaderAndInfo } from '../../../core/models/headerAndnfo';
import { HeaderAndTextComponent } from '../../../shared/components/header-and-text/header-and-text.component';
import { LeftImageRightTextComponent } from '../../../shared/components/left-image-right-text/left-image-right-text.component';
import { RightImageLeftTextComponent } from '../../../shared/components/right-image-left-text/right-image-left-text.component';
import { SubHeaderPageImageContainerComponent } from '../../../shared/components/sub-header-page-image-container/sub-header-page-image-container.component';

@Component({
  selector: 'app-intrinsically-safe-radios',
  standalone: true,
  imports: [SubHeaderPageImageContainerComponent, LeftImageRightTextComponent, RightImageLeftTextComponent, HeaderAndTextComponent],
  templateUrl: './intrinsically-safe-radios.component.html',
  styleUrls: ['./intrinsically-safe-radios.component.scss']
})
export class IntrinsicallySafeRadiosComponent {

  imageContent: HeaderAndInfo = {
    header: 'Intrinsically Safe Radios',
    headerExplanationPara: '',
  };

  textContent0: HeaderAndInfo = {
    header: 'What is an Intrinsically Safe Radio?',
    headerExplanationPara: `Perhaps you may come across the term "intrinsically safe" when looking for and buying radios. Then you must be wondering what is an intrinsically safe radio? What does it do? What's the difference between it and other radios? Why use an intrinsically safe radio? Intrinsically safe radios are radios that can be used safely in explosive atmospheres.`,
  };

  textContent1: HeaderAndInfo = {
    header: 'What is an explosive environment?',
    headerExplanationPara: `An explosive environment is an area in which combustible gases or dust are present sufficient to cause an explosion. Workplaces that involve the manufacture processing, handling, storage, and transport of explosive substances in industries like oil and petroleum, chemical, coal, pharmaceutical, and food processing could become an explosive environment.`,
  };

  textContent2: HeaderAndInfo = {
    header: 'Three conditions must be met for an explosion to occur:',
    headerExplanationPara: `1, Existing explosive substances such as hydrogen, acetylene, methane, dust, and flammable fibers reaching certain density;
    2, Presence of oxygen;
    3, Ignition sources, including electrical sparks, mechanical sparks, electrostatic sparks, high heat, and light energy.`,
  };

  textContent3: HeaderAndInfo = {
    header: 'Industry',
    headerExplanationPara: `In industries like oil and petroleum, natural gas, chemical, mining, and airports where the leakage of explosive substances is common, when using various electrical systems, due to the ubiquity of oxygen, fire sources will inevitably appear in the production process, so special attention should be paid to explosion protection.`,
  };

  textContent4: HeaderAndInfo = {
    header: 'Intrinsically safe radio',
    headerExplanationPara: `The intrinsically safe radio is a device that can be used in a dangerous environment. It can ensure that no static electricity and sparks are generated during use, eliminate hidden dangers in production safety, and ensure safe and smooth communication.`,
  };

  textContent5: HeaderAndInfo = {
    header: 'What is the difference between Non-Incendive and Intrinsically Safe?',
    headerExplanationPara: `Two-way radio communication is very important and even critical in the explosive working environment mentioned above, but standard two-way radios should not be used because they may make a potentially hazardous situation even more dangerous, so this environment requires the use of intrinsically safe radios.
    To meet intrinsic safety standards, radios are designed to prevent even the smallest possibility of sparking during use. They also had to limit the heat generated by the radio. Batteries used in radios must also be specially designed to prevent sparks and eliminate short circuits. Even the design and construction materials of the radio enclosure itself must prevent or eliminate friction, which can create static electricity and create sparks. In addition to radios, any accessories used, such as microphones and headphones, need to be intrinsically safe.
    Due to these stricter manufacturing requirements, intrinsically safe radios are more expensive than Non-Incendives. Of course, the security considerations built into these radios are worth much more than that. After all, security is priceless.
    `,
  };

  textContent6: HeaderAndInfo = {
    header: 'Different types of Intrinsically Safe Radios',
    headerExplanationPara: `Whether it is an intrinsically safe two-way radio is not determined by itself, but must be certified by the explosion-proof standard system. Jurisdictions differ in their certification standards and systems to qualify a product as explosion-proof. Here we take a look at the main certification bodies:`,
  };

  textContent7: HeaderAndInfo = {
    header: 'IECEx',
    headerExplanationPara: `IECEx is the explosion-proof certification promoted by the International Electrotechnical Commission (IEC). Its purpose is to standardize equipment and services worldwide to promote international trade while maintaining high standards of equipment safety. The current certification for explosive atmospheres is IEC 60079.`,
  };

  textContent8: HeaderAndInfo = {
    header: 'ATEX',
    headerExplanationPara: `The ATEX Directive is the certification for “equipment and protective systems intended for use in potentially explosive atmospheres” adopted by the European Commission. Its purpose is to create a single market within Europe, eliminate technical barriers to trade, and ensure that equipment intended for use in potentially explosive atmospheres can circulate freely among member states.`,
  };

  textContent9: HeaderAndInfo = {
    header: 'NEC',
    headerExplanationPara: `The American explosion-proof certification system (NEC: National Electrical Code) is divided into two major systems: Division and Zone. The Division system (ie NEC500) adopts the explosion-proof mark of the United States. The main standards are UL913, TIA-4950-A, etc., Zone system (NEC505/506) adopts the explosion-proof standard consistent with the IEC system, and the standard used is UL 60079.`,
  };

  textContent10: HeaderAndInfo = {
    header: 'Saikia Intrinsically Safe Radios',
    headerExplanationPara: `Work safety is a core mission of Saikia. From its years of continuous in-depth research, Saikia has developed a series of intrinsically safe radios. It continues to undertake technological innovation to achieve the ultimate explosion-proof performance for its products. The certifications and approvals for use in environments with inflammable and explosive gases and dust that the models in its family of intrinsically safe radios have achieved are IECEx(international), ATEX(EU), NEC(US&CA), CCC-Ex(CN). These models can be widely used in the energy industry, such as in oil and natural gas, and other areas in mining, the chemical industry, airport, firefighting, and dangerous chemicals management, to ensure a safe production and operation environment.`,
  };

}
